export interface Template {
  id: string;
  label: string;
  desc: string;
  html: string;
  variants?: Record<string, string>;
}

function getHtml(t: Template, style: string): string {
  if (style === "default" || !t.variants?.[style]) return t.html;
  return t.variants[style];
}

export function resolveTemplate(t: Template, style: string): Template {
  return { ...t, html: getHtml(t, style) };
}

// ── Base palette ──
// default: warm cream #FBF8EF, ink #1a1a1a
// neon:    deep dark #0a0a14, electric cyan/magenta
// brutalist: white #fff, black #000
// pixel/geometric/organic: use default palette but adapted rendering

export const TEMPLATES: Template[] = [
  {
    id: "blank",
    label: "Blank Canvas",
    desc: "Start from nothing",
    html: "",
  },
  {
    id: "particles",
    label: "Particle Field",
    desc: "Drifting particles",
    html: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const pts=Array.from({length:60},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3,r:Math.random()*2+1,o:Math.random()*.3+.1}));function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fillStyle='rgba(26,26,26,'+p.o+')';x.fill()});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    variants: {
      pixel: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}canvas{image-rendering:pixelated}</style></head><body><canvas id="c"></canvas><script>try{const S=6,c=document.getElementById('c'),x=c.getContext('2d');const W=Math.ceil(innerWidth/S),H=Math.ceil(innerHeight/S);c.width=W;c.height=H;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.imageSmoothingEnabled=false;const pal=['#2b2b2b','#5a3a1a','#8b6c42','#b89f6a'];const pts=Array.from({length:40},()=>({x:Math.random()*W|0,y:Math.random()*H|0,vx:Math.random()<.5?-1:1,vy:Math.random()<.5?-1:1,ci:Math.random()*pal.length|0}));let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,W,H);pts.forEach(p=>{t%3===0&&(p.x+=p.vx,p.y+=p.vy);if(p.x<0||p.x>=W)p.vx*=-1;if(p.y<0||p.y>=H)p.vy*=-1;x.fillStyle=pal[p.ci];x.fillRect(p.x,p.y,1,1)});t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      geometric: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const pts=Array.from({length:40},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.4,vy:(Math.random()-.5)*.4,sides:Math.floor(Math.random()*4)+3,r:Math.random()*8+4,rot:Math.random()*Math.PI*2,rv:(Math.random()-.5)*.02}));function poly(cx,cy,r,n,rot){x.beginPath();for(let i=0;i<n;i++){const a=rot+i*Math.PI*2/n;x.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r)}x.closePath()}function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.rot+=p.rv;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;poly(p.x,p.y,p.r,p.sides,p.rot);x.strokeStyle='rgba(26,26,26,0.2)';x.lineWidth=1;x.stroke()});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      organic: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const pts=Array.from({length:35},()=>{const a=Math.random()*Math.PI*2;return{x:Math.random()*c.width,y:Math.random()*c.height,vx:Math.cos(a)*.2,vy:Math.sin(a)*.2,r:Math.random()*6+3,phase:Math.random()*Math.PI*2}});let t=0;function draw(){x.fillStyle='rgba(251,248,239,0.08)';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{const wobble=Math.sin(t*.01+p.phase)*0.3;p.vx+=wobble*.01;p.vy+=Math.cos(t*.01+p.phase)*.01;const speed=Math.sqrt(p.vx*p.vx+p.vy*p.vy);if(speed>.4){p.vx*=.4/speed;p.vy*=.4/speed}p.x+=p.vx;p.y+=p.vy;if(p.x<0)p.x=c.width;if(p.x>c.width)p.x=0;if(p.y<0)p.y=c.height;if(p.y>c.height)p.y=0;const r=p.r+Math.sin(t*.02+p.phase)*2;x.beginPath();x.arc(p.x,p.y,r,0,Math.PI*2);x.fillStyle='rgba(26,26,26,0.03)';x.fill()});t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      brutalist: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#fff;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const pts=Array.from({length:50},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.6,vy:(Math.random()-.5)*.6,s:Math.random()*4+2}));function draw(){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;x.fillStyle='#000';x.fillRect(p.x-p.s/2,p.y-p.s/2,p.s,p.s)});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      neon: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#0a0a14;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const cols=['#00fff2','#ff00e6','#7b61ff','#00ff88'];const pts=Array.from({length:50},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.4,vy:(Math.random()-.5)*.4,r:Math.random()*2+1,ci:Math.random()*cols.length|0}));function draw(){x.fillStyle='rgba(10,10,20,0.15)';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.shadowColor=cols[p.ci];x.shadowBlur=12;x.fillStyle=cols[p.ci];x.fill();x.shadowBlur=0});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    },
  },
  {
    id: "dotgrid",
    label: "Dot Grid",
    desc: "Breathing grid of dots",
    html: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const sp=40,cols=Math.ceil(c.width/sp),rows=Math.ceil(c.height/sp);let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=i*sp+sp/2,cy=j*sp+sp/2;const d=Math.sqrt((cx-c.width/2)**2+(cy-c.height/2)**2);const s=Math.sin(t*.02+d*.01)*1.5+2.5;const o=Math.sin(t*.015+d*.008)*.15+.2;x.beginPath();x.arc(cx,cy,s,0,Math.PI*2);x.fillStyle='rgba(26,26,26,'+o+')';x.fill()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    variants: {
      pixel: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}canvas{image-rendering:pixelated}</style></head><body><canvas id="c"></canvas><script>try{const S=6,c=document.getElementById('c'),x=c.getContext('2d');const W=Math.ceil(innerWidth/S),H=Math.ceil(innerHeight/S);c.width=W;c.height=H;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.imageSmoothingEnabled=false;const sp=8,cols=Math.ceil(W/sp),rows=Math.ceil(H/sp);let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,W,H);for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=i*sp+sp/2|0,cy=j*sp+sp/2|0;const d=Math.sqrt((cx-W/2)**2+(cy-H/2)**2);const on=Math.sin(t*.03+d*.05)>.1;if(on){x.fillStyle='#1a1a1a';x.fillRect(cx,cy,2,2)}}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      geometric: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const sp=50,cols=Math.ceil(c.width/sp),rows=Math.ceil(c.height/sp);let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=i*sp+sp/2,cy=j*sp+sp/2;const d=Math.sqrt((cx-c.width/2)**2+(cy-c.height/2)**2);const rot=t*.01+d*.005;const s=4+Math.sin(t*.02+d*.01)*3;x.save();x.translate(cx,cy);x.rotate(rot);x.strokeStyle='rgba(26,26,26,'+(Math.sin(t*.015+d*.008)*.15+.2)+')';x.lineWidth=1;x.strokeRect(-s,-s,s*2,s*2);x.restore()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      organic: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const sp=45,cols=Math.ceil(c.width/sp),rows=Math.ceil(c.height/sp);let t=0;function draw(){x.fillStyle='rgba(251,248,239,0.1)';x.fillRect(0,0,c.width,c.height);for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=i*sp+sp/2,cy=j*sp+sp/2;const d=Math.sqrt((cx-c.width/2)**2+(cy-c.height/2)**2);const wobX=Math.sin(t*.01+i*.3+j*.2)*4;const wobY=Math.cos(t*.012+j*.3+i*.2)*4;const s=Math.sin(t*.02+d*.01)*2.5+3;const o=Math.sin(t*.015+d*.008)*.12+.15;x.beginPath();x.arc(cx+wobX,cy+wobY,s,0,Math.PI*2);x.fillStyle='rgba(26,26,26,'+o+')';x.fill()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      brutalist: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#fff;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const sp=35,cols=Math.ceil(c.width/sp),rows=Math.ceil(c.height/sp);let t=0;function draw(){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=i*sp+sp/2,cy=j*sp+sp/2;const d=Math.sqrt((cx-c.width/2)**2+(cy-c.height/2)**2);const s=Math.sin(t*.025+d*.012)>0?sp*.35:0;if(s>0){x.fillStyle='#000';x.fillRect(cx-s/2,cy-s/2,s,s)}}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      neon: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#0a0a14;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const sp=40,cols=Math.ceil(c.width/sp),rows=Math.ceil(c.height/sp);const pal=['#00fff2','#ff00e6','#7b61ff'];let t=0;function draw(){x.fillStyle='rgba(10,10,20,0.2)';x.fillRect(0,0,c.width,c.height);for(let i=0;i<cols;i++)for(let j=0;j<rows;j++){const cx=i*sp+sp/2,cy=j*sp+sp/2;const d=Math.sqrt((cx-c.width/2)**2+(cy-c.height/2)**2);const s=Math.sin(t*.02+d*.01)*2+2.5;const ci=((i+j+Math.floor(t*.01))%pal.length);const o=Math.sin(t*.015+d*.008)*.3+.4;x.beginPath();x.arc(cx,cy,s,0,Math.PI*2);x.shadowColor=pal[ci];x.shadowBlur=8;x.fillStyle=pal[ci];x.globalAlpha=o;x.fill();x.globalAlpha=1;x.shadowBlur=0}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    },
  },
  {
    id: "waveform",
    label: "Waveform",
    desc: "Undulating sine wave",
    html: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);for(let w=0;w<3;w++){x.beginPath();const off=w*0.8,op=.12-.03*w;for(let i=0;i<=c.width;i+=2){const y=c.height/2+Math.sin(i*.008+t*.02+off)*80+Math.sin(i*.003+t*.01+off)*40;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.strokeStyle='rgba(26,26,26,'+op+')';x.lineWidth=1.5;x.stroke()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    variants: {
      pixel: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}canvas{image-rendering:pixelated}</style></head><body><canvas id="c"></canvas><script>try{const S=4,c=document.getElementById('c'),x=c.getContext('2d');const W=Math.ceil(innerWidth/S),H=Math.ceil(innerHeight/S);c.width=W;c.height=H;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.imageSmoothingEnabled=false;let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,W,H);const pal=['#1a1a1a','#5a3a1a','#8b6c42'];for(let w=0;w<3;w++){x.fillStyle=pal[w];for(let i=0;i<W;i++){const y=H/2+Math.sin(i*.04+t*.02+w*.8)*H*.15|0;x.fillRect(i,y,1,2)}}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      geometric: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);for(let w=0;w<4;w++){x.beginPath();const off=w*0.6;for(let i=0;i<=c.width;i+=30){const y=c.height/2+Math.sin(i*.008+t*.02+off)*80;x.save();x.translate(i,y);x.rotate(t*.01+i*.005);const s=6+w*2;x.strokeStyle='rgba(26,26,26,'+(0.15-w*.03)+')';x.lineWidth=1;x.strokeRect(-s/2,-s/2,s,s);x.restore()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      organic: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='rgba(251,248,239,0.06)';x.fillRect(0,0,c.width,c.height);for(let w=0;w<5;w++){x.beginPath();const off=w*0.5,op=.08-.01*w;for(let i=0;i<=c.width;i+=2){const n1=Math.sin(i*.006+t*.015+off)*90;const n2=Math.sin(i*.002+t*.008+off*2)*50;const n3=Math.sin(i*.01+t*.025+w)*20;const y=c.height/2+n1+n2+n3;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.strokeStyle='rgba(26,26,26,'+op+')';x.lineWidth=2;x.stroke()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      brutalist: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#fff;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.beginPath();for(let i=0;i<=c.width;i+=1){const y=c.height/2+Math.sin(i*.008+t*.025)*80+(Math.random()-.5)*4;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.strokeStyle='#000';x.lineWidth=2;x.stroke();x.beginPath();x.moveTo(0,c.height/2);x.lineTo(c.width,c.height/2);x.strokeStyle='rgba(0,0,0,0.1)';x.lineWidth=1;x.stroke();t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      neon: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#0a0a14;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const cols=['#00fff2','#ff00e6','#7b61ff'];let t=0;function draw(){x.fillStyle='rgba(10,10,20,0.12)';x.fillRect(0,0,c.width,c.height);cols.forEach((col,w)=>{x.beginPath();const off=w*0.8;for(let i=0;i<=c.width;i+=2){const y=c.height/2+Math.sin(i*.008+t*.02+off)*80+Math.sin(i*.003+t*.01+off)*40;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.shadowColor=col;x.shadowBlur=15;x.strokeStyle=col;x.lineWidth=2;x.stroke();x.shadowBlur=0});t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    },
  },
  {
    id: "circle",
    label: "Breathing Circle",
    desc: "Pulsing concentric rings",
    html: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);const cx=c.width/2,cy=c.height/2;for(let i=5;i>=0;i--){const base=30+i*35;const r=base+Math.sin(t*.02+i*.5)*12;const o=.06+(.04*(5-i));x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.strokeStyle='rgba(26,26,26,'+o+')';x.lineWidth=1;x.stroke()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    variants: {
      pixel: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}canvas{image-rendering:pixelated}</style></head><body><canvas id="c"></canvas><script>try{const S=4,c=document.getElementById('c'),x=c.getContext('2d');const W=Math.ceil(innerWidth/S),H=Math.ceil(innerHeight/S);c.width=W;c.height=H;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.imageSmoothingEnabled=false;let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,W,H);const mx=W/2,my=H/2;for(let i=5;i>=0;i--){const base=8+i*9;const r=base+Math.sin(t*.02+i*.5)*3|0;const o=.1+(.06*(5-i));x.strokeStyle='rgba(26,26,26,'+o+')';x.lineWidth=1;x.beginPath();for(let a=0;a<Math.PI*2;a+=Math.PI/16){const px=mx+Math.cos(a)*r|0,py=my+Math.sin(a)*r|0;if(a===0)x.moveTo(px,py);else x.lineTo(px,py)}x.closePath();x.stroke()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      geometric: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);const cx=c.width/2,cy=c.height/2;for(let i=6;i>=0;i--){const sides=3+i;const base=25+i*30;const r=base+Math.sin(t*.02+i*.5)*10;const rot=t*.005*(i%2===0?1:-1);const o=.06+(.035*(6-i));x.save();x.translate(cx,cy);x.rotate(rot);x.beginPath();for(let s=0;s<=sides;s++){const a=s*Math.PI*2/sides-Math.PI/2;x.lineTo(Math.cos(a)*r,Math.sin(a)*r)}x.closePath();x.strokeStyle='rgba(26,26,26,'+o+')';x.lineWidth=1;x.stroke();x.restore()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      organic: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='rgba(251,248,239,0.08)';x.fillRect(0,0,c.width,c.height);const cx=c.width/2,cy=c.height/2;for(let i=5;i>=0;i--){const base=30+i*35;const o=.04+(.03*(5-i));x.beginPath();for(let a=0;a<Math.PI*2;a+=.02){const wobble=Math.sin(a*3+t*.02+i)*8+Math.sin(a*7+t*.015)*4;const r=base+Math.sin(t*.02+i*.5)*12+wobble;x.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r)}x.closePath();x.strokeStyle='rgba(26,26,26,'+o+')';x.lineWidth=1.5;x.stroke()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      brutalist: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#fff;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;let t=0;function draw(){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const cx=c.width/2,cy=c.height/2;for(let i=5;i>=0;i--){const base=30+i*35;const r=base+Math.sin(t*.025+i*.5)*12;const lw=i===0?3:1;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.strokeStyle='#000';x.lineWidth=lw;x.stroke()}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      neon: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#0a0a14;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const cols=['#00fff2','#ff00e6','#7b61ff','#00ff88','#ffcc00','#ff4444'];let t=0;function draw(){x.fillStyle='rgba(10,10,20,0.12)';x.fillRect(0,0,c.width,c.height);const cx=c.width/2,cy=c.height/2;for(let i=5;i>=0;i--){const base=30+i*35;const r=base+Math.sin(t*.02+i*.5)*12;x.beginPath();x.arc(cx,cy,r,0,Math.PI*2);x.shadowColor=cols[i%cols.length];x.shadowBlur=20;x.strokeStyle=cols[i%cols.length];x.lineWidth=2;x.stroke();x.shadowBlur=0}t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    },
  },
  {
    id: "constellation",
    label: "Constellation",
    desc: "Connected drifting stars",
    html: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const N=30,pts=Array.from({length:N},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.2,vy:(Math.random()-.5)*.2}));function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1});for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(d<150){x.beginPath();x.moveTo(pts[i].x,pts[i].y);x.lineTo(pts[j].x,pts[j].y);x.strokeStyle='rgba(26,26,26,'+(1-d/150)*.1+')';x.stroke()}}pts.forEach(p=>{x.beginPath();x.arc(p.x,p.y,2,0,Math.PI*2);x.fillStyle='rgba(26,26,26,.25)';x.fill()});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    variants: {
      pixel: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}canvas{image-rendering:pixelated}</style></head><body><canvas id="c"></canvas><script>try{const S=4,c=document.getElementById('c'),x=c.getContext('2d');const W=Math.ceil(innerWidth/S),H=Math.ceil(innerHeight/S);c.width=W;c.height=H;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.imageSmoothingEnabled=false;const N=20,pts=Array.from({length:N},()=>({x:Math.random()*W|0,y:Math.random()*H|0,vx:Math.random()<.5?-1:1,vy:Math.random()<.5?-1:1}));let t=0;function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,W,H);if(t%2===0)pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>=W)p.vx*=-1;if(p.y<0||p.y>=H)p.vy*=-1});for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(d<40){x.strokeStyle='rgba(26,26,26,0.15)';x.beginPath();x.moveTo(pts[i].x,pts[i].y);x.lineTo(pts[j].x,pts[j].y);x.stroke()}}pts.forEach(p=>{x.fillStyle='#1a1a1a';x.fillRect(p.x,p.y,2,2)});t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      geometric: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const N=25,pts=Array.from({length:N},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,sides:Math.floor(Math.random()*3)+3,rot:0,rv:(Math.random()-.5)*.03}));function draw(){x.fillStyle='#FBF8EF';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.rot+=p.rv;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1});for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(d<150){x.beginPath();x.moveTo(pts[i].x,pts[i].y);x.lineTo(pts[j].x,pts[j].y);x.strokeStyle='rgba(26,26,26,'+(1-d/150)*.1+')';x.lineWidth=1;x.stroke()}}pts.forEach(p=>{x.save();x.translate(p.x,p.y);x.rotate(p.rot);x.beginPath();for(let s=0;s<=p.sides;s++){const a=s*Math.PI*2/p.sides;x.lineTo(Math.cos(a)*5,Math.sin(a)*5)}x.closePath();x.strokeStyle='rgba(26,26,26,0.25)';x.lineWidth=1;x.stroke();x.restore()});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      organic: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#FBF8EF;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const N=25;let t=0;const pts=Array.from({length:N},()=>({x:Math.random()*c.width,y:Math.random()*c.height,phase:Math.random()*Math.PI*2}));function draw(){x.fillStyle='rgba(251,248,239,0.06)';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=Math.sin(t*.008+p.phase)*.5;p.y+=Math.cos(t*.006+p.phase)*.5;if(p.x<0)p.x=c.width;if(p.x>c.width)p.x=0;if(p.y<0)p.y=c.height;if(p.y>c.height)p.y=0});for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(d<180){x.beginPath();x.moveTo(pts[i].x,pts[i].y);const mx=(pts[i].x+pts[j].x)/2+Math.sin(t*.01+i)*15;const my=(pts[i].y+pts[j].y)/2+Math.cos(t*.01+j)*15;x.quadraticCurveTo(mx,my,pts[j].x,pts[j].y);x.strokeStyle='rgba(26,26,26,'+(1-d/180)*.06+')';x.lineWidth=1.5;x.stroke()}}pts.forEach(p=>{const r=3+Math.sin(t*.02+p.phase)*1.5;x.beginPath();x.arc(p.x,p.y,r,0,Math.PI*2);x.fillStyle='rgba(26,26,26,0.08)';x.fill()});t++;requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      brutalist: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#fff;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const N=30,pts=Array.from({length:N},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3}));function draw(){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1});for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(d<120){x.beginPath();x.moveTo(pts[i].x,pts[i].y);x.lineTo(pts[j].x,pts[j].y);x.strokeStyle='#000';x.lineWidth=d<60?2:1;x.stroke()}}pts.forEach(p=>{x.fillStyle='#000';x.fillRect(p.x-3,p.y-3,6,6)});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
      neon: `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;padding:0}body{background:#0a0a14;overflow:hidden}</style></head><body><canvas id="c"></canvas><script>try{const c=document.getElementById('c'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const cols=['#00fff2','#ff00e6','#7b61ff','#00ff88'];const N=30,pts=Array.from({length:N},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,ci:Math.random()*cols.length|0}));function draw(){x.fillStyle='rgba(10,10,20,0.15)';x.fillRect(0,0,c.width,c.height);pts.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1});for(let i=0;i<N;i++)for(let j=i+1;j<N;j++){const d=Math.hypot(pts[i].x-pts[j].x,pts[i].y-pts[j].y);if(d<150){x.beginPath();x.moveTo(pts[i].x,pts[i].y);x.lineTo(pts[j].x,pts[j].y);const col=cols[pts[i].ci];x.shadowColor=col;x.shadowBlur=6;x.strokeStyle=col;x.globalAlpha=(1-d/150)*.4;x.lineWidth=1;x.stroke();x.globalAlpha=1;x.shadowBlur=0}}pts.forEach(p=>{x.beginPath();x.arc(p.x,p.y,3,0,Math.PI*2);x.shadowColor=cols[p.ci];x.shadowBlur=10;x.fillStyle=cols[p.ci];x.fill();x.shadowBlur=0});requestAnimationFrame(draw)}draw()}catch(e){}</script></body></html>`,
    },
  },
];
